image: docker:latest

stages:
  - build

build-docker:
  stage: build
  script:
     - whoami
     - docker -v
     - docker login --username=mikesoon@yahoo.com registry-intl.ap-southeast-3.aliyuncs.com
