image: docker:latest

services:
  - docker:18.09.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_REGISTRY_IMAGE_URL: "registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome/"
  DOCKER_REGISTRY_USERNAME: "mikesoon@yahoo.com"
  DOCKER_REGISTRY_PASSWORD: "Mikesoon!@#123"
  K8S_MASTER_PUBLIC_IP: "47.254.192.44"
  K8S_PASSWORD: "Mikesoon!@#123"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
     - docker login --username=mikesoon@yahoo.com registry-intl.ap-southeast-3.aliyuncs.com --password='Mikesoon!@#123'
     - docker build -t awesome-project .
     - docker tag awesome-project registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     - docker push registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     
production:
  image: roffe/kubectl:latest
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="${K8S_MASTER_PUBLIC_IP}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -f deployment.yaml
  only:
    - master