image: docker:stable

services:
  - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REGISTRY_IMAGE_URL: "registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome/"
  DOCKER_REGISTRY_USERNAME: "mikesoon@yahoo.com"
  DOCKER_REGISTRY_PASSWORD: "Mikesoon!@#123"
  #K8S_MASTER_PUBLIC_IP: "47.254.192.44"
  #K8S_PASSWORD: "Mikesoon!@#123"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  KUBECONFIG: /etc/deploy/config
  
stages:
  - test
  - build
  - deploy

test:
  image: maven:latest
  stage: test
  only:
    - master
  artifacts:
    paths:
    - target/*.jar
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=https://sonarqube.mktechconsulting.co -Dsonar.login=admin
  tags:
    - k8s-runner
    
build:
  stage: build
  script:
     - docker login --username=mikesoon@yahoo.com registry-intl.ap-southeast-3.aliyuncs.com --password='Mikesoon!@#123'
     - docker build -t awesome-project .
     - docker tag awesome-project registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     - docker push registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
  tags:
  - k8s-runner
  
production:
  image: roffe/kubectl:latest
  stage: deploy
  script:
    #- kubectl config set-cluster k8s --server="${K8S_MASTER_PUBLIC_IP}"
    #- kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    #- kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    #- kubectl config set-context default --cluster=k8s --user=gitlab
    #- kubectl config use-context default
    
    - mkdir -p /etc/deploy
    - echo $kube_config |base64 -d > $KUBECONFIG
    - kubectl apply -f deployment.yaml
  only:
    - master
  tags:
  - k8s-runner