image: docker:stable

before_script:
  - docker info

stages:
  - build
  - deploy

build:
  stage: build
  script:
     - docker info
     - docker login --username=mikesoon@yahoo.com registry-intl.ap-southeast-3.aliyuncs.com --password='Mikesoon!@#123'
     - docker build -t awesome-project .
     - docker tag awesome-project registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     - docker push registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     
deploy:
  image: registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
  stage: deploy
  tags:
    - k8s-runner
  script:
    - mkdir -p /etc/deploy
    - echo $kube_config |base64 -d > $KUBECONFIG
    - sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml

