image: docker:stable

variables:
  DOCKER_REGISTRY_IMAGE_URL: "registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome"
  DOCKER_REGISTRY_USERNAME: "mikesoon@yahoo.com"
  DOCKER_REGISTRY_PASSWORD: "Mikesoon!@#123"
  K8S_MASTER_PUBLIC_IP: "47.254.192.44"
  K8S_PASSWORD: "Mikesoon!@#123"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
     - docker login --username=mikesoon@yahoo.com registry-intl.ap-southeast-3.aliyuncs.com --password='Mikesoon!@#123'
     - docker build -t awesome-project .
     - docker tag awesome-project registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     - docker push registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
     
production:
  image: registry-intl.ap-southeast-3.aliyuncs.com/ns-acr-ais/awesome:latest
  stage: deploy
  script:
    - apk add --update --no-cache openssh sshpass
    - mkdir -p $HOME/.kube
    - sshpass -p "$K8S_PASSWORD" scp -o StrictHostKeyChecking=no root@$K8S_MASTER_PUBLIC_IP:/etc/kubernetes/kube.conf $HOME/.kube/config
    - cat deployment.yml | sed "s|\$DOCKER_REGISTRY_IMAGE_URL|$DOCKER_REGISTRY_IMAGE_URL|g" | kubectl apply -f -
  only:
    - master