apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplejavaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplejavaapp
  template:
    metadata:
      labels:
        app: simplejavaapp
    spec:
      containers:
      - name: simplejavaapp
        image: registry.cn-beijing.aliyuncs.com/gitlab-demo/java-demo:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simplejavaapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: simplejavaapp
  selector:
    app: simplejavaapp
  type: LoadBalancer
